name: test
on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  test:
    permissions:
      contents: write
      checks: write
    runs-on: ubuntu-latest
    container: ohmyfish/ohmyfish
    steps:
      - name: Change current working directory owner and group
        run: sudo chown -R nemo:nemo .
      - name: print stuff
        run: |
         whoami
         pwd
         ls -lhart
         echo $GITHUB_WORKSPACE
         touch foo
      - uses: actions/checkout@v3
        with:
          path: .
      # - name: Install plugin from current working directory
      #   run: fish -c "omf install (pwd)"
      - name: Run tests
        run: fish -l test/bootstrap.fish
